"""Initial public schema"""

from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column_mappings', sa.Text(), nullable=True),
    sa.Column('parser_config', sa.Text(), nullable=True),
    sa.Column('value_mappings', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('broker_import_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('column_mappings', sa.Text(), nullable=True),
    sa.Column('value_mappings', sa.Text(), nullable=True),
    sa.Column('parser_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hourly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('avg_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overall_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('break_even_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loss_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('gross_loss', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('largest_profit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_trade_duration', sa.Integer(), nullable=True),
    sa.Column('longest_win_streak', sa.Integer(), nullable=True),
    sa.Column('longest_loss_streak', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('current_streak_type', sa.String(length=10), nullable=True),
    sa.Column('mfe_capture', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mae_recovery', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('efficiency_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_risk_reward', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('exit_gap', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('left_on_table', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('good_captures', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=20), nullable=True),
    sa.Column('strike', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('put_call', sa.String(length=5), nullable=True),
    sa.Column('open_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('avg_entry_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_commissions', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('first_entry_date', sa.Date(), nullable=True),
    sa.Column('last_update_date', sa.Date(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_underlying_symbol'), 'positions', ['underlying_symbol'], unique=False)
    op.create_table('trade_tags_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_users_single_owner'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('broker_format_id', sa.Integer(), nullable=True),
    sa.Column('broker_import_mapping_id', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_format_id'], ['broker_formats.id'], ),
    sa.ForeignKeyConstraint(['broker_import_mapping_id'], ['broker_import_mappings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('break_even_trades', sa.Integer(), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('largest_profit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('avg_trade_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'account_id', name='uix_daily_stats_date_account')
    )
    op.create_index('ix_daily_stats_date_account', 'daily_stats', ['date', 'account_id'], unique=False)
    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('broker_format_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('executions_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['broker_format_id'], ['broker_formats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=20), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('strike', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('put_call', sa.String(length=5), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_commissions', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('entry_execution_ids', sa.Text(), nullable=True),
    sa.Column('exit_execution_ids', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('open_qty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('override_auto_description', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_underlying_symbol'), 'trades', ['underlying_symbol'], unique=False)
    op.create_table('combined_trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combined_trade_id', sa.Integer(), nullable=False),
    sa.Column('original_trade_ids', sa.Text(), nullable=False),
    sa.Column('original_trades_data', sa.Text(), nullable=False),
    sa.Column('trade_executions_map', sa.Text(), nullable=False),
    sa.Column('is_undone', sa.Boolean(), nullable=True),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['combined_trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.String(length=50), nullable=True),
    sa.Column('account_alias', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('underlying_symbol', sa.String(length=20), nullable=True),
    sa.Column('strike', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('put_call', sa.String(length=5), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('exec_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('proceeds', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('net_cash', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('broker_execution_commission', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('commission_currency', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('matched_trade_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('exec_datetime', sa.DateTime(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('settle_date', sa.Date(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['import_history.id'], ),
    sa.ForeignKeyConstraint(['matched_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_symbol'), 'executions', ['symbol'], unique=False)
    op.create_index(op.f('ix_executions_trade_date'), 'executions', ['trade_date'], unique=False)
    op.create_index(op.f('ix_executions_trade_id'), 'executions', ['trade_id'], unique=False)
    op.create_table('trade_tags',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['trade_tags_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id', 'tag_id')
    )
    op.create_table('position_executions',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('position_id', 'execution_id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError('Automatic downgrade is disabled. Restore a verified backup instead.')
