"""add journal tables"""

from alembic import op
import sqlalchemy as sa


revision = '0002_journal'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_journals_date'), 'daily_journals', ['date'], unique=True)
    op.create_table('event_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('journal_event_tags',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('event_tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_tag_id'], ['event_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['daily_journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('journal_id', 'event_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError('Automatic downgrade is disabled. Restore a verified backup instead.')
